//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace images_sql_server.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagene
    {
        public int id { get; set; }
        public byte[] img { get; set; }
        public string nombre { get; set; }
    }
}
